export const productType = {
    ADD_TO_CART: 'ADD_TO_CART',
    ASYNC_LOAD_ALL: 'ASYNC_LOAD_ALL',
    ASYNC_LOAD_QUERY: 'ASYNC_LOAD_QUERY',
    DECREMENT_AMOUNT: 'DECREMENT_AMOUNT',
    DO_CHECKOUT: 'DO_CHECKOUT',
    INCREMENT_AMOUNT: 'INCREMENT_AMOUNT',
    IS_LOADING: 'IS_LOADING',
    LOAD_ALL: 'LOAD_ALL',
    LOAD_QUERY: 'LOAD_QUERY',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
};